config/routes.rb
Pool1::Application.routes.draw do

  resources :groups# do
  resources :training_times, :only=> [:create, :destroy]

  resource :pools#, as: "pools", :controller => 'pools'
  root :to => 'pools#show'
  resources :instructors do#, :controller => 'instructors'
   resources :groups
  end
  resources :trainings, :only=> [:create, :destroy, :update]

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :trainings, :dependent => :destroy
  has_many :groups, :through => :trainings
  validates :name_instructor, :presence => true,:uniqueness => true
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructor = Instructor.all
    #@group=Group.first

    #@in_i=Instructor.find(7)
    #@i_i= @group.trainings
    #@i_i1= @group.trainings.find_by_instructor_id(@in_i.id)

  end
  def new
    @instructor=Instructor.new

  end

  def edit
    @instructor=Instructor.find(params[:id])
  end

  def show
    @instructor=Instructor.find(params[:id])
    @training_times=TrainingTime.new
  end

  def destroy
     @instructor=Instructor.find(params[:id])
     @instructor.destroy
    redirect_to  instructors_path
  end

  def update
     @instructor=Instructor.find(params[:id])
    @instructor.update_attributes(params[:instructor]) ? (redirect_to instructor_path)  : (render 'edit')
  end

  def create
    @instructor=Instructor.new(params[:instructor])
    @instructor.save ? (redirect_to instructor_path(@instructor)) : (render 'new')
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form_instructor.html.erb
<%= render 'layouts/errors', :message_error=>@instructor %>
<%= f.label "Instructor" %>
<%= f.text_field :name_instructor %>
<% if @instructor.id.nil? %>
<%= f.submit "Sozdat'" %>
<% else %>
<%= f.submit "Izmenit'" %>
<% end %>
<div class="centering_buttons">
<%= link_to "Nazad", instructors_path,:class =>"link_button round" %></div>

app/views/instructors/_instructor.html.erb
<li><%= link_to instructor.name_instructor, instructor_path(instructor) %>
  <% g_id_n=0 %>
  <% number_group=0 %>
  <% instructor.groups.order(:id).each do |group| %>
  <% g_id=group.id %>
      <%if g_id!=g_id_n    %>
         <% g_id_n=g_id %>
          <% number_group+=1 %>
      <% end %>
      <% end %>
  <%="Vedet #{instructor.trainings.count} zaniatii v #{number_group} gr."  %>
  <%= link_to "Izmenit'", edit_instructor_path(instructor) %>
  <%= link_to "Udalit'",{action: :destroy, :id=>instructor.id}  ,method: :delete, confirm: "V nature?", title: "Udalit' #{instructor.name_instructor}" %></li>

app/views/instructors/_table_sessions.html.erb
<table border="hidden">
  <tr>
    <td> Day week </td> <td>Name group</td><td>Beginning workout</td><td>Duration workout</td><td> </td>
  </tr>
  <% %w{pn vt sr cht pt sb vs}.each do |dw| %>
      <% day_week=dw %>
      <% day_week_old="" %>

      <% @training_times.find_all{|t| t[:day_of_the_week]=~/#{dw}/}.each do |training_times| %>


          <tr>  <%unless day_week_old==day_week  %>
                <td> <%= training_times.day_of_the_week %></td>
                <% day_week_old=day_week %>
            <% else %>
                <td> </td>
            <% end %>
            <td> <%= link_to Group.find(training_times.group_id).name_group, instructor_group_path(@instructor.id,training_times.group_id) %> </td>
            <td><%= training_times.time_workout %> </td>
            <td> <%= training_times.duration_of_workout %></td>
            <td> <%= link_to "Udalit'", {:action => :destroy, :controller => :trainings, :group_id=>training_times.group_id, :instructor_id=>@instructor.id,:training_time_id =>training_times.id },:method => :delete,:confirm => "Horosho podumali?"%></td>
          </tr>

      <% end  %>
  <% end %> </table>

app/views/instructors/edit.html.erb
<h1>Instructors#edit</h1>
<p>Find me in app/views/Instructors/edit.html.erb</p>
<% form_for @instructor do |f| %>
    <%= render 'form_instructor', f: f%>
<% end %>

app/views/instructors/index.html.erb
<h1>Instructors#index</h1>
<p>Find me in app/views/Instructors/index.html.erb</p>
<p>rrrr</p>
<div class="round">
   <%= render @instructor %>
  <!--< %= @group %><br/>
  < %= @i_i %><br/>
  < %= @i_i1 %><br/>
  @i_i1.instructor_id:< %= @i_i1.instructor_id %><br/>
  @i_i1.group_id:< %= @i_i1.group_id %><br/> -->
</div>
<%= link_to "Dobavit' Instructora", new_instructor_path, :class => "button_to_create round" %>

app/views/instructors/new.html.erb
<h1>Instructors#new</h1>
<p>Find me in app/views/Instructors/new.html.erb</p>
<%= form_for :instructor, url:{action: :create} do |f|%>
<%= render 'form_instructor', :f=>f %>



<% end %>

app/views/instructors/show.html.erb
<h1>Instructors#show</h1>
<p>Find me in app/views/Instructors/show.html.erb</p>
<h2> <%= @instructor.name_instructor %></h2>
 <% g_id_n=0 %>

<% array_training_times=[] %>
<% @instructor.groups.order(:id).each do |groups|  %>
    <%g_id=groups.id%>
    <%@group=Group.find(groups.id)  %>

    <% if g_id_n!=g_id %>
        <% g_id_n=g_id %>



      <!-- < %= groups.name_group %>

 < %= Training.find_all_by_instructor_id_and_group_id(params[:instructor_id],params[:group_id]).each do |training| %> -->
          <% Training.find_all_by_instructor_id_and_group_id(@instructor.id,groups.id).each do |training| %>
       <% @training_times=(TrainingTime.find(training.training_time_id)) %>
          <% array_training_times<<@training_times.id %>


          <% end %>


        <% end %>

<% end %>

<!-- %= @training_times=TrainingTime.all(:conditions =>{:group_id=>array_groups,:id=>[array_training_times]} ) %>
< %= @training_times=TrainingTime.where(:id=>array_training_times) % -->

<%@training_times=TrainingTime.order("day_of_the_week ASC, time_workout ASC").find_all_by_id(array_training_times) %>
<% unless @training_times.blank? %>
<%= render 'table_sessions' %>
<% end %>
<br/>
<div class="centering_buttons">
 <%= link_to "Dobavilenie gruppy", instructor_groups_path(@instructor),:class =>"link_button round" %>
<%= link_to "Izmenit'", edit_instructor_path(@instructor),:class =>"link_button round" %>
<%= link_to "K spisku instruktorov", instructors_path,:class =>"link_button round" %>
</div>
<%=  %>