config/routes.rb
Pool1::Application.routes.draw do

  resources :groups# do
  resources :training_times, :only=> [:create, :destroy]

  resource :pools#, as: "pools", :controller => 'pools'
  root :to => 'pools#show'
  resources :instructors do#, :controller => 'instructors'
   resources :groups
  end
  resources :trainings, :only=> [:create, :destroy, :update]

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessor :summary_number
  parameter_pool = Pool.first
  s_p = parameter_pool.size_pool.to_i
  n_m = parameter_pool.men_locker_room.to_i
  n_w = parameter_pool.women_locker_room.to_i
  #tut=Group.new(:name_group=>:name_group)
  #{:tut_m => tut.number_of_men.to_i }#+tut.number_of_women
  #{:tut_m=>5}
  #tut_m = tut.number_of_men
  #{:tut=>[:group][:number_of_men]}
  #{:tut=>5}#limit_number_of_group = 4 #@tuttt verno(4)()     self.verno()params[:number_of_womens].to_i(:number_of_womens).ext self([:group][:number_of_womens].)(self.find_by_number_of_womens(:number_of_womens)[:number_of_womens])Group.new(params[:number_of_womens]).new(params[:id]).const_get(:number_of_mens).to_i@group(params[:number_of_mens]) + Group.new(params[:number_of_womens])
  #g_m=Group.new(:group).number_of_men

  attr_accessible :name_group,:number_of_men,:number_of_women,:day_of_the_week,:time_workout
  validates :name_group, :presence => true,:uniqueness => true
  #validates_numericality_of limit_number_of_group, :less_than_or_equal_to => s_p,
  #                           :message => "Chislo mujchin i jenschin v gruupe bol'she rasmera basseina'"
  #validates_numericality_of :verno, :less_than_or_equal_to => s_p, :message => "Chislo #{@tuttt} i #{limit_number_of_group} mujchin i jenschin v gruupe bol'she rasmera basseina #{s_p}"
  #validates_numericality_of :summary_number, :less_than_or_equal_to=> s_p
  validates_numericality_of :number_of_men , :less_than_or_equal_to => n_m#,:message => "TUT_M #{g_m}"
  validates_numericality_of :number_of_women, :less_than_or_equal_to => n_w
  has_many :trainings, :dependent => :destroy
  has_many :instructors, :through => :trainings
  has_many :training_times, :dependent => :destroy
  def verno
    limit_number_of_group = @tuttt
    return limit_number_of_group
        if @tuttt.blank? then
          @tuttt= 100#
        else
          0
        end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @title="Spisok grupp"
    @group=Group.all
    @instructor = Instructor.find_by_id(params[:instructor_id])
  end

  def new
    @title="Novaia gruppa"
    @group=Group.new

  end

  def show
    @title="Sostav gruppy"
    @group=Group.find_by_id(params[:id])
    @training_time=@group.training_times
    @instructor=Instructor.find_by_id(params[:instructor_id])
    @instructor_group=@group.instructors
    @training=@group.trainings
  end
  def edit
    @title="Redaktirovanie gruppy"
    @group=Group.find_by_id(params[:id])
    #@index_g=params[:index_g]
  end
  def create
    @group=Group.new(params[:group])
    #{:tut=>5}

    #@tuttt1=params[:group][:number_of_men].to_s.to_i
    #@tuttt=Group.new(params[:group])
    if @group.save then
      redirect_to group_path(@group)
    else
      render 'new'
    end

  end
  def update
     @group=Group.find(params[:id])
    @group.update_attributes(params[:group]) ? (redirect_to group_path) : (render 'edit')#(@group))
  end
  def destroy
    Group.find(params[:id]).destroy
    redirect_to groups_path
  end


end

app/helpers/groups_helper.rb
module GroupsHelper

end

app/views/groups/_form_group.html.erb
<%= render 'layouts/errors', :message_error=>@group %>
params[:index_g]<%= @index_g.nil? %>
<%= f.label "Nazvanie gruppy" %>
<%= f.text_field :name_group %><br />
<%= f.label "Kolichestvo mujchin ne > #{Pool.first.men_locker_room}" %>
<%= f.text_field :number_of_men %><br />
<%= f.label "Kolichestvo jenschin ne > #{Pool.first.women_locker_room}" %>
<%= f.text_field :number_of_women %><br />
<%= @group1=Group.new(params[:group]) %>
<%= @group1.number_of_men %>
<%= @group1.number_of_women %>
<%= f.hidden_field :summary_number, :value=>@group1.number_of_men.to_i %>
<% if @group.id.nil? %>
    <%=	 f.submit "Sozdat'" %>
    <div class="centering_buttons">
      <%=	 link_to "Nazad k spisku grupp", groups_path,:class =>"link_button round" %>
    </div>
<% else %>

    <%= f.submit "Izmenit'" %>
    <div class="centering_buttons">
      <%=	 link_to "Nazad", group_path(@group.id),:class =>"link_button round" %>
    </div>
<%end%>
<!--% if @index_g %>

    < % else %>

< % end %-->

app/views/groups/_group.html.erb
    <li>
      <% if @instructor.nil? %>
          <%= link_to group.name_group, group%>
          <%= link_to "Izmenit'",edit_group_path(group), {:index_g=>1} %>
          <%= link_to "udalit'", {:action => :destroy,:id=> group.id} , :method => :delete, :confirm => "Chto pravda?", :title => "Udalit' #{group.name_group}" %>
          <!-- |  < %= link_to "Nill" %> -->

      <% else %>
          <%= link_to group.name_group, instructor_group_path(@instructor.id,group.id)%>
          <% unless group.training_times.blank? %>
          |  <%= link_to "Trenerovat' gruppu na vseh zaniatiiah", {:action => :create,:controller => :trainings,:group_id=>group.id,:instructor_id=>@instructor.id}, :method => :post %>
          <!-- < %= group.submit "Dobavit' gruppu", %> -->
              <% else %>
          | Zaniati' net
          <% end %>
      <% end %>
    </li>

app/views/groups/edit.html.erb
<h1>EDIT Group</h1>

<%= form_for @group, url:{action: :update} do |f| %>
    <%= render 'form_group', :f=>f %>


<% end %>

app/views/groups/index.html.erb
<h1>Grupy#spisok_g</h1>
<p>Find me in app/views/grupy/index.html.erb</p>
<%= render @group %>

<%= link_to "Novaia gruppa", new_group_path, :class => "button_to_create round"  %>

app/views/groups/new.html.erb
<h1>Grupy#novaia</h1>
<p>Find me in app/views/grupy/novaia.html.erb</p>
Kolichestvo mujchin i jenschi v summe ne > <%= Pool.first.size_pool %> <%= @tuttt  %>

<%= form_for :group, url:{action: :create} do |f| %>
   <%= render 'form_group',:f=>f %>

<% end %>

app/views/groups/show.html.erb
<h1>Grupy#sostav_g</h1>
<p>Find me in app/views/grupy/sostav_g.html.erb</p>

    <ul> Nazvanie gruppy: <%= @group.name_group %></ul>
<ul>Kolichestvo mujchin v gruppe: <%= @group.number_of_men%></ul>
  <ul>Kolichestvo jenschin v gruppe: <%= @group.number_of_women %></ul>
  <!-- <li>
    < %=@instructor.groups %><br/>
    < %= @training_time.group %>
  </li> -->


<div class="time_workout">   <% %w{pn vt sr cht pt sb vs}.each do |dn| %>

    <% unless @group.training_times.find_all_by_day_of_the_week(dn).blank? %>
    <h2> <%= "Den' nedeli: #{dn}" %></h2>
<%= render :partial => "training_times/training_times",:collection => @group.training_times.order("time_workout ASC").find_all_by_day_of_the_week(dn) %>
    <% end %>
 <% end %></div>


<% unless params[:instructor_id].blank? %>
    <div class="centering_buttons">
<%= link_to "K spisku grupp", instructor_groups_path ,:class =>"link_button round"%>
<%= link_to "K sebe #{@instructor.name_instructor}", instructor_path(@instructor.id) ,:class =>"link_button round"%>
    </div>
<% else %>
    <%= render 'training_times/time_workout' %>
    <div class="centering_buttons">
    <%= link_to "K spisku grupp", groups_path,:class =>"link_button round" %>
    <%= link_to "Izmenit'", edit_group_path,:class =>"link_button round" %>
    </div>
<% end %>